#Logger configuration
logger:
  console:
    enabled: true
    enable_color: false
    log_level: ${LOG_LEVEL:debug}

#Prometheus configuration
#prometheus:
#  path: ${PROMETHEUS_PATH:/metrics}
#  enabled: ${PROMETHEUS_ENABLED:yes}
#  port: ${PROMETHEUS_PORT:2112}

listen:
  address: ${LISTEN_ADDRESS:0.0.0.0:162}
  community: ${LISTEN_COMMUNITY}

redis:
  enabled: true
  address: ${REDIS_ADDRESS:wca-redis:6379}
  password: ${REDIS_PASSWORD}
  database: ${REDIS_DB:0}
  channel: ${REDIS_CHANNEL:snmptrap}

