logger:
  console:
    enabled: true
    enable_color: false
    log_level: ${LOG_LEVEL:debug}

#Prometheus configuration
#prometheus:
#  path: ${PROMETHEUS_PATH:/metrics}
#  enabled: ${PROMETHEUS_ENABLED:yes}
#  port: ${PROMETHEUS_PORT:2112}

listen:
  address: ${LISTEN_ADDRESS:0.0.0.0:162}
  community: ${LISTEN_COMMUNITY} #Leave empty for disable checking

redis:
  enabled: false
  address: ${REDIS_ADDRESS:wca-redis:6379}
  password: ${REDIS_PASSWORD}
  channel: ${REDIS_CHANNEL:trapservice}

script_handler:
  enabled: true
  count_handlers: 10
  queue_size: 500
  command: docker exec -i trapservice:handler
